version: "2"
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    environment:
      MONGODB: "mongodb+srv://app:Q0vB8TmNuIzoaNOc@truckingcluster.jgyo6.mongodb.net/truckingcluster?retryWrites=true&w=majority"
      MONGO_PW: Q0vB8TmNuIzoaNOc
#   postgres:
#     image: postgres:9.6.2-alpine
#     environment:
#       POSTGRES_USER: todoapp
#       POSTGRES_DB: todos
